from datetime import datetime

from nightfall.reporters.base import BaseReporter


CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
.container { max-width: 1200px; margin: 0 auto; }
h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #38bdf8; }
h2 { font-size: 1.3rem; margin: 1.5rem 0 0.75rem; color: #94a3b8; }
.summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
.card { background: #1e293b; padding: 1.25rem; border-radius: 12px; border: 1px solid #334155; }
.card .num { font-size: 2rem; font-weight: 700; color: #38bdf8; }
.card .label { font-size: 0.85rem; color: #64748b; margin-top: 0.25rem; }
table { width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 12px; overflow: hidden; margin: 1rem 0; }
th { background: #334155; padding: 0.75rem 1rem; text-align: left; font-weight: 600; color: #94a3b8; }
td { padding: 0.75rem 1rem; border-top: 1px solid #334155; }
tr:hover td { background: #1e3a5f; }
.critical { color: #ef4444; font-weight: 700; }
.high { color: #f97316; font-weight: 600; }
.medium { color: #eab308; }
.low { color: #22c55e; }
.info { color: #64748b; }
.badge { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 6px; font-size: 0.75rem; font-weight: 600; }
.badge-open { background: #166534; color: #86efac; }
.badge-closed { background: #7f1d1d; color: #fca5a5; }
.footer { text-align: center; margin-top: 2rem; color: #475569; font-size: 0.8rem; }
"""


class HTMLReporter(BaseReporter):
    def format_name(self):
        return "html"

    def generate(self, findings, metadata=None):
        summary = self._summarize(findings)
        rows = "".join(self._target_row(f) for f in findings)
        meta_rows = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in (metadata or {}).items())
        vuln_total = sum(len(f.get("vulnerabilities", [])) for f in findings)
        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Nightfall Scan Report</title><style>{CSS}</style></head>
<body><div class="container">
<h1>Nightfall Scan Report</h1>
<p>{summary['generated_at']}</p>
<div class="summary">
<div class="card"><div class="num">{summary['total_targets']}</div><div class="label">Targets Scanned</div></div>
<div class="card"><div class="num">{summary['open_ports']}</div><div class="label">Open Ports</div></div>
<div class="card"><div class="num">{vuln_total}</div><div class="label">Vulnerabilities</div></div>
<div class="card"><div class="num">{summary['critical']}</div><div class="label">Critical</div></div>
</div>
{"<h2>Metadata</h2><table>" + meta_rows + "</table>" if metadata else ""}
<h2>Findings</h2>
<table><thead><tr><th>Host</th><th>Port</th><th>Service</th><th>Status</th><th>Vulnerabilities</th></tr></thead><tbody>{rows}</tbody></table>
<div class="footer"><p>Generated by Nightfall Vulnerability Scanner</p></div>
</div></body></html>"""

    def _target_row(self, f):
        host = f.get("host", "?")
        port = str(f.get("port", ""))
        service = f.get("service", "unknown")
        status = f.get("status", "unknown")
        badge = f'<span class="badge badge-{"open" if status == "open" else "closed"}">{status}</span>'
        vulns = "<br>".join(
            f'<span class="{v.get("severity", "info")}">{v.get("id", "")} — {v.get("name", "")}</span>'
            for v in f.get("vulnerabilities", [])
        ) or "<span class='info'>None</span>"
        return f"<tr><td>{host}</td><td>{port}</td><td>{service}</td><td>{badge}</td><td>{vulns}</td></tr>"

    def _summarize(self, findings):
        breakdown = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in findings:
            for v in f.get("vulnerabilities", []):
                sev = v.get("severity", "info")
                if sev in breakdown:
                    breakdown[sev] += 1
        return {
            "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            "total_targets": len(findings),
            "open_ports": sum(1 for f in findings if f.get("status") == "open"),
            "closed_ports": sum(1 for f in findings if f.get("status") == "closed"),
            **breakdown,
        }
